package org.app.appfilm.Constant;

public enum MsgConstant {
  //NOT_FOUND
  USER_NOT_FOUND,
  MOVIE_NOT_FOUND,
  ROLE_NOT_FOUND,
  COMMENT_NOT_FOUND,
  COUNTRY_NOT_FOUND,
  CATEGORY_NOT_FOUND,
  ACTRESS_NOT_FOUND,

  // SUCCESS_UPDATE
  SUCCESS_UPDATE_USER,
  SUCCESS_UPDATE_MOVIE,
  SUCCESS_UPDATE_ROLE,
  SUCCESS_UPDATE_COMMENT,
  SUCCESS_UPDATE_COUNTRY,
  SUCCESS_UPDATE_CATEGORY,
  SUCCESS_UPDATE_ACTRESS,

  // NOT_SUCCESS_UPDATE
  NOT_SUCCESS_UPDATE_USER,
  NOT_SUCCESS_UPDATE_MOVIE,
  NOT_SUCCESS_UPDATE_ROLE,
  NOT_SUCCESS_UPDATE_COMMENT,
  NOT_SUCCESS_UPDATE_COUNTRY,
  NOT_SUCCESS_UPDATE_CATEGORY,
  NOT_SUCCESS_UPDATE_ACTRESS,

  // SUCCESS_DELETE
  SUCCESS_DELETE_USER,
  SUCCESS_DELETE_MOVIE,
  SUCCESS_DELETE_ROLE,
  SUCCESS_DELETE_COMMENT,
  SUCCESS_DELETE_COUNTRY,
  SUCCESS_DELETE_CATEGORY,
  SUCCESS_DELETE_ACTRESS,

  // NOT_SUCCESS_DELETE
  NOT_SUCCESS_DELETE_USER,
  NOT_SUCCESS_DELETE_MOVIE,
  NOT_SUCCESS_DELETE_ROLE,
  NOT_SUCCESS_DELETE_COMMENT,
  NOT_SUCCESS_DELETE_COUNTRY,
  NOT_SUCCESS_DELETE_CATEGORY,
  NOT_SUCCESS_DELETE_ACTRESS
}
